<script setup lang="ts">
/**
 * Donut breakdown of prompt composition (JCLAW-690 follow-up).
 *
 * Renders one arc per entry, sized by token share, with a legend carrying the
 * exact numbers. Deliberately hand-rolled SVG rather than a chart dependency —
 * the same call the LatencyOverlayChart makes, and a single-series donut is a
 * few `stroke-dasharray` sums.
 *
 * Every entry gets its own arc — there is no "Other" bucket. A prompt runs to
 * ~50 contributors and most are under 2%, so the tail is a band of slivers, but
 * collapsing it hid the very thing the chart is read for: where the bytes went.
 * The legend is the readable surface for the tail, and it closes with a total
 * row so the shares can be checked against the dialog's header figures.
 */
import { computed } from 'vue'
import type { PromptBreakdownEntry } from '~/types/api'

const props = withDefaults(defineProps<{
  entries: PromptBreakdownEntry[]
  /** Denominator for share %. Omit to normalise within this series, which is
   *  what the prompt breakdown does — its one chart already spans every
   *  contributor, so the arcs should close at exactly 100%. Pass an explicit
   *  total only when a series is a known part of a larger whole. */
  total?: number
  label: string
}>(), { total: 0 })

// Curated palette for the leading slices — the arcs big enough to identify by
// colour alone. Picked to stay distinguishable in both themes and to avoid the
// red reserved for destructive affordances elsewhere in the admin UI.
const COLORS = [
  '#2dd4bf', '#60a5fa', '#a78bfa', '#f0abfc',
  '#fbbf24', '#34d399', '#818cf8', '#fb923c',
  '#22d3ee', '#a3e635', '#f472b6', '#94a3b8',
]

// Past the curated set the series is an open-ended tail, so colours are
// generated by golden-angle hue rotation rather than wrapping the palette with
// `% length` (which repeats a colour inside one chart). Consecutive indices are
// adjacent arcs — slices are sorted by size — and the golden angle puts them
// almost opposite each other on the wheel, which is exactly the pair that has
// to stay tellable apart.
const GOLDEN_ANGLE = 137.508

function sliceColor(i: number): string {
  const curated = COLORS[i]
  if (curated) return curated
  // Start the generated ramp off 0° so it doesn't open on destructive-red.
  const hue = (30 + (i - COLORS.length + 1) * GOLDEN_ANGLE) % 360
  return `hsl(${hue.toFixed(1)}, 62%, 62%)`
}

const RADIUS = 60
const STROKE = 26
const CIRCUMFERENCE = 2 * Math.PI * RADIUS

const seriesTotal = computed(() => props.entries.reduce((n, e) => n + e.tokens, 0))
const seriesChars = computed(() => props.entries.reduce((n, e) => n + e.chars, 0))
/** Share denominator: explicit total when given, else the series itself. Guarded
 *  against 0 so an all-empty series renders a track rather than dividing by zero. */
const denominator = computed(() => props.total || seriesTotal.value || 1)

const slices = computed(() => {
  const ranked = [...props.entries].filter(e => e.tokens > 0).sort((a, b) => b.tokens - a.tokens)
  // Walk a running offset so each arc starts where the previous ended.
  let offset = 0
  return ranked.map((e, i) => {
    const fraction = e.tokens / denominator.value
    const arc = {
      name: e.name,
      chars: e.chars,
      tokens: e.tokens,
      color: sliceColor(i),
      fraction,
      dash: fraction * CIRCUMFERENCE,
      offset: -offset * CIRCUMFERENCE,
    }
    offset += fraction
    return arc
  })
})

/**
 * Closing row for the legend, so the chart can be reconciled against the
 * dialog's header figures without re-adding 50 numbers by hand.
 *
 * Chars are summed straight from the entries and land on the header's total
 * exactly — sections are contiguous, non-overlapping spans of the prompt string
 * and tool schemas are the rest of it. Tokens are re-derived from that char sum
 * rather than summed off the rows: every row is its own `round(chars / 4)`, so
 * adding the rounded parts drifts a token or two from the header, which rounds
 * the whole once. Rounding once at the end is both the more accurate estimate
 * and the one the header shows.
 */
const totals = computed(() => ({
  chars: seriesChars.value,
  tokens: Math.round(seriesChars.value / 4),
  fraction: slices.value.reduce((n, s) => n + s.fraction, 0),
}))

// Legend flanks the donut, so it splits down the middle and reads the way the
// arcs are ordered: biggest first, down the left column, then down the right.
// The larger half goes left when the count is odd.
const legendColumns = computed(() => {
  const half = Math.ceil(slices.value.length / 2)
  return [slices.value.slice(0, half), slices.value.slice(half)]
})

const pct = (f: number) => `${(f * 100).toFixed(1)}%`

/** Text alternative for the graphic — the donut is decorative on its own, so the
 *  accessible name carries the same ranking a sighted user reads off the arcs. */
const summary = computed(() =>
  `${props.label}: ${seriesTotal.value.toLocaleString()} tokens. `
  + slices.value.map(s => `${s.name} ${pct(s.fraction)}`).join(', '))
</script>

<template>
  <div class="py-4">
    <!-- Donut centred between the two legend halves. Stacked below lg — three
         columns can't hold their widths on a narrow viewport — where `order`
         floats the donut back above the legend so the graphic still leads. -->
    <div class="flex flex-col lg:flex-row items-center lg:items-start gap-6">
      <svg
        :viewBox="`0 0 ${(RADIUS + STROKE) * 2} ${(RADIUS + STROKE) * 2}`"
        class="w-56 h-56 lg:w-72 lg:h-72 shrink-0 -rotate-90 order-1 lg:order-2 lg:self-center"
        role="img"
        :aria-label="summary"
      >
        <circle
          :cx="RADIUS + STROKE"
          :cy="RADIUS + STROKE"
          :r="RADIUS"
          fill="none"
          stroke="currentColor"
          class="text-border"
          :stroke-width="STROKE"
        />
        <circle
          v-for="s in slices"
          :key="s.name"
          :cx="RADIUS + STROKE"
          :cy="RADIUS + STROKE"
          :r="RADIUS"
          fill="none"
          :stroke="s.color"
          :stroke-width="STROKE"
          :stroke-dasharray="`${s.dash} ${CIRCUMFERENCE - s.dash}`"
          :stroke-dashoffset="s.offset"
        >
          <title>{{ s.name }} — {{ s.tokens.toLocaleString() }} tokens ({{ pct(s.fraction) }})</title>
        </circle>
      </svg>

      <ul
        v-for="(column, col) in legendColumns"
        :key="col"
        class="flex-1 min-w-0 w-full space-y-1 text-xs"
        :class="col === 0 ? 'order-2 lg:order-1' : 'order-3'"
      >
        <li
          v-for="s in column"
          :key="s.name"
          class="flex items-center gap-2"
        >
          <span
            class="w-2.5 h-2.5 shrink-0"
            :style="{ backgroundColor: s.color }"
            aria-hidden="true"
          />
          <span class="flex-1 truncate text-fg-primary font-mono">{{ s.name }}</span>
          <span class="tabular-nums text-fg-muted w-16 text-right">{{ s.chars.toLocaleString() }}</span>
          <span class="tabular-nums text-fg-muted w-14 text-right">{{ s.tokens.toLocaleString() }}</span>
          <span class="tabular-nums text-fg-muted w-12 text-right">{{ pct(s.fraction) }}</span>
        </li>
      </ul>
    </div>

    <!-- Totals span the full width rather than closing one column: they add up
         both halves, and tucking them under the right one would read as that
         column's subtotal. -->
    <div
      class="flex items-center gap-2 mt-3 pt-2 border-t border-border text-xs font-semibold"
      data-testid="donut-total"
    >
      <span class="flex-1 truncate text-fg-strong font-mono">Total</span>
      <span class="tabular-nums text-fg-primary w-16 text-right">{{ totals.chars.toLocaleString() }}</span>
      <span class="tabular-nums text-amber-300 w-14 text-right">{{ totals.tokens.toLocaleString() }}</span>
      <span class="tabular-nums text-emerald-700 dark:text-emerald-400 w-12 text-right">{{ pct(totals.fraction) }}</span>
    </div>
  </div>
</template>
